# Generated by Django 3.2.25 on 2024-06-04 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('fname', models.CharField(max_length=30, verbose_name='First name')),
                ('mname', models.CharField(max_length=30, verbose_name='Middle  name')),
                ('sname', models.CharField(max_length=30, verbose_name='Sir name')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('nati_id', models.IntegerField(verbose_name='National ID')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(choices=[('DRIVER', 'Driver'), ('MECHANICAL ENGINEER', 'Mechanical Engineer'), ('RECEPTIONIST', 'Receptionist')], max_length=20, verbose_name='Position')),
                ('dor', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Registration')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
    ]
